import { NEWS } from "./NEWS";
export const COMMENTS = [
  {
    id: 0,
    newsId: NEWS[0].id,
    author: "John Doe",
    content: "This is a great post!",
    timestamp: "2023-04-07T09:15:00Z",
  },
  {
    id: 1,
    newsId: NEWS[0].id,
    author: "Jane Smith",
    content: "Thanks for sharing this information!",
    timestamp: "2023-04-06T14:30:00Z",
  },
  {
    id: 2,
    newsId: NEWS[1].id,
    author: "Bob Johnson",
    content: "I have a question about this topic.",
    timestamp: "2023-04-05T11:45:00Z",
  },
  {
    id: 3,
    newsId: NEWS[0].id,
    author: "Samantha Lee",
    content: "This post really helped me out, thanks!",
    timestamp: "2023-04-04T08:00:00Z",
  },
  {
    id: 4,
    newsId: NEWS[1].id,
    author: "David Kim",
    content: "I completely disagree with your point of view.",
    timestamp: "2023-04-03T13:20:00Z",
  },
  {
    id: 5,
    newsId: NEWS[0].id,
    author: "Emily Chen",
    content: "Can you explain this in more detail?",
    timestamp: "2023-04-02T10:10:00Z",
  },
  {
    id: 6,
    newsId: NEWS[1].id,
    author: "Peter Wong",
    content: "Great job, keep up the good work!",
    timestamp: "2023-04-01T15:50:00Z",
  },
  {
    id: 7,
    newsId: NEWS[2].id,
    author: "Sarah Kim",
    content: "I have a suggestion for a future post.",
    timestamp: "2023-03-31T11:30:00Z",
  },
  {
    id: 8,
    newsId: NEWS[0].id,
    author: "Mike Smith",
    content: "This post is really informative, thank you!",
    timestamp: "2023-03-30T07:40:00Z",
  },
  {
    id: 9,
    newsId: NEWS[1].id,
    author: "Lisa Lee",
    content: "I found a typo in this post, just wanted to let you know.",
    timestamp: "2023-03-29T12:15:00Z",
  },
];
